language: php

php: 5.5

before_script :
  - composer install
  - mysql -e 'create database tigerkitstarterapp;'
  - mysql -e "use mysql; SET PASSWORD FOR 'travis'@'localhost' = PASSWORD('travis'); FLUSH PRIVILEGES;"

after_script:
  - CODECLIMATE_REPO_TOKEN="56ae8752566df6c0e22abe158730d3ab8a64dbe733906869a665c0cb05a70592" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

script: phpunit

notifications:
  email:
    - matthew@baggett.me
  slack: thruio:m7cGYXmdz261AkGDfiRVBHmY
