  <!-- start: Meta -->
  <meta charset="utf-8">
  <title><?php echo $this->getSiteTitle(); ?></title>
  <meta name="description" content="<?php echo $this->getSiteTitle(); ?>">
  <meta name="author" content="Matthew Baggett <matthew@baggett.me>">
  <!-- end: Meta -->

  <!-- start: Mobile Specific -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end: Mobile Specific -->

  <!-- start: CSS -->
  <?php foreach ($this->getCSS() as $css): ?>
    <link id="base-style" href="<?php echo $this->url($css); ?>" rel="stylesheet">
  <?php endforeach; ?>
  <!-- end: CSS -->

  <!-- start: JS -->
  <?php foreach ($this->getJS() as $js): ?>
    <script src="<?php echo $this->url($js); ?>"></script>
  <?php endforeach; ?>
  <!-- end: JS -->

  <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- start: Favicon -->
  <link rel="shortcut icon" href="<?php echo $this->url("favicon.ico"); ?>">
  <!-- end: Favicon -->

  <script>
    var app_root = '<?php echo $this->url("/"); ?>';
  </script>
