<?php $thisUser = \TigerKit\Models\User::getCurrent();?>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<?=$this->url("/"); ?>"><?= \TigerKit\TigerApp::Config("Application Name"); ?></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <?php if($thisUser): ?>
          <li><?=$this->l("things", "My Things"); ?></li>
        <?php endif; ?>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <?php if($thisUser): ?>
          <li><?=$this->l("dashboard",$thisUser->username); ?></li>
          <li><?=$this->l("logout","Logout"); ?></li>
        <?php else: ?>
          <li><?=$this->l("login","Login"); ?></li>
        <?php endif; ?>
      </ul>

    </div>
    <!--/.nav-collapse -->
  </div>
</nav>