'Application Name': 'Tiger Starter App'
Copyright: 'Your Name Here'
'Debug Mode': 'On'
Databases:
    Default: { Type: Mysql, Host: localhost, Port: 3306, Username: tiger, Password: tiger, Database: tiger }
Caches:
    Default: { Type: Redis, Host: localhost, Port: 6379, Database: 5 }
