'Application Name': 'Tiger Starter App'
Copyright: 'Your Name Here'
'Debug Mode': 'On'
Databases:
    Default: { Type: Sqlite, File: starterapp.sqlite }
Caches:
    Default: { Type: Redis, Host: localhost, Port: 6379, Database: 5 }
Storage:
    Default: { Type: Zip, Location: assets/datablob.zip }
