'Application Name': 'Tiger Starter App'
Copyright: 'Your Name Here'
'Debug Mode': 'On'
Databases:
    Default: { Type: Mysql, Host: localhost, Port: 3306, Username: travis, Password: travis, Database: tigerkitstarterapp }

